/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Turnos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fede0
 */
public class Laboratorio extends javax.swing.JInternalFrame {
private DefaultTableModel dtmLaboratorio;
    /**
     * Creates new form Laboratorio
     */
    public Laboratorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        String []jTitulo={"Nombre","Horario Inicial","Horario Final"};
        String[][]jDatos={};

        dtmLaboratorio= new DefaultTableModel(jDatos,jTitulo);

        try{
            Class.forName("org.gjt.mm.mysql.Driver");
            // Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123123");
            Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123");
            Statement stm= cnx.createStatement();
            ResultSet rst= stm.executeQuery("SELECT nombre,horario_inicio, horario_final from laboratorio;");

            while(rst.next()){
                String [] registro= {rst.getString("nombre"),rst.getString("horario_inicio"),rst.getString("horario_final")};
                dtmLaboratorio.addRow(registro);
            }

        }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
        }catch (SQLException sqle){
            sqle.printStackTrace();
        }
        jTableLabo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jTableLabo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableLabo.setModel(dtmLaboratorio);
        jTableLabo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLaboMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLabo);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(228, 228, 228));
        jTextArea2.setColumns(5);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Seleccionar analisis para");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("visualizar su descripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLaboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLaboMouseClicked
        int fila=jTableLabo.getSelectedRow();
        String info=jTableLabo.getModel().getValueAt(fila,0).toString();
        String registro="";
        jTextArea2.setText("");
        try{
        Class.forName("org.gjt.mm.mysql.Driver");
        //Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123123");
         Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123");
        Statement stm= cnx.createStatement();
        ResultSet rst= stm.executeQuery("SELECT descripcion from laboratorio where nombre='"+info+"';");
        
        while(rst.next()){
         registro=rst.getString("descripcion");
            jTextArea2.setText(registro);
        }
        cnx.close();
        }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
        }catch (SQLException sqle){
            sqle.printStackTrace();
        }
        
    }//GEN-LAST:event_jTableLaboMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableLabo;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
