
package Turnos;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author fede0
 */
public class TurnoConsulta extends javax.swing.JInternalFrame {
private DefaultTableModel dtmTurno;

    public TurnoConsulta() {
        initComponents();
        buttonGroup1.add(jradioDNI);
        buttonGroup1.add(jradioNroTurno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jradioDNI = new javax.swing.JRadioButton();
        jradioNroTurno = new javax.swing.JRadioButton();
        jTextDato = new javax.swing.JTextField();
        jConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        String [] jTitulo = {"Nro","Dni Paciente","Medico","Dia y Hora"};
        String [][] jDatos = {};

        dtmTurno = new DefaultTableModel (jDatos,jTitulo);
        jTableConsulta = new javax.swing.JTable();
        jDescartar = new javax.swing.JButton();

        setClosable(true);

        jradioDNI.setText("DNI");

        jradioNroTurno.setText("Nro de Turno");

        jTextDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDatoActionPerformed(evt);
            }
        });
        jTextDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDatoKeyTyped(evt);
            }
        });

        jConsultar.setText("Consultar");
        jConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarActionPerformed(evt);
            }
        });

        jTableConsulta = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableConsulta.setModel(dtmTurno);
        jScrollPane1.setViewportView(jTableConsulta);

        jDescartar.setText("Descartar");
        jDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescartarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextDato, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jradioDNI)
                .addGap(14, 14, 14)
                .addComponent(jradioNroTurno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDescartar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioDNI)
                    .addComponent(jradioNroTurno)
                    .addComponent(jTextDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDescartar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarActionPerformed
        limpiarTabla();
        String colum= "";
        if (jradioDNI.isSelected()){colum="dni_paciente";}
        if (jradioNroTurno.isSelected()){colum="id";}
        if (colum==""){
            JOptionPane.showMessageDialog( this, "Elija DNI o Nro de Turno","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if (jTextDato.getText().isEmpty()){
            JOptionPane.showMessageDialog( this, "Ingrese DNI o Nro de Turno","Error", JOptionPane.ERROR_MESSAGE);
            }
        else{
            int dato=Integer.parseInt(jTextDato.getText());
        try{
        Class.forName("org.gjt.mm.mysql.Driver");
       // Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123123");
        Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123");
        Statement stm= cnx.createStatement();
        ResultSet rst= stm.executeQuery("SELECT t.id,t.dni_paciente,m.nombre,m.apellido,t.fecha FROM turno t INNER JOIN medico m ON m.dni=t.dni_medico WHERE "+colum+"= "+dato+" and t.fecha<='"+ObtenerFecha()+" 00:00:00' ORDER BY fecha;");
       // ResultSet rst= stm.executeQuery("SELECT t.id,t.dni_paciente,m.nombre,m.apellido,t.fecha FROM turno t INNER JOIN medico m ON m.dni=t.dni_medico WHERE "+colum+"= "+dato+" ORDER BY fecha;");
        
        
        while(rst.next()){
        String [] registro= {rst.getString("id"),rst.getString("dni_paciente"),rst.getString("nombre") +" "+rst.getString("apellido"),rst.getString("fecha")};
        dtmTurno.addRow(registro);
        }
        jTextDato.setText("");
        buttonGroup1.clearSelection();
        }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
        }catch (SQLException sqle){
            sqle.printStackTrace();
        }
        }
        }
    }//GEN-LAST:event_jConsultarActionPerformed

    private void jDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescartarActionPerformed

       if (!jTableConsulta.isRowSelected(jTableConsulta.getSelectedRow())){
           JOptionPane.showMessageDialog( this, "Seleccione turno a descartar","Error", JOptionPane.ERROR_MESSAGE);
       }else{
       int fila=jTableConsulta.getSelectedRow();
        String info=jTableConsulta.getModel().getValueAt(fila,0).toString();
            
            try{
                Class.forName("org.gjt.mm.mysql.Driver");
               // Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123123");
                Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123");
                Statement stm= cnx.createStatement();

                int res= stm.executeUpdate("UPDATE turno SET dni_paciente=0 WHERE id="+info+";");
                if (res==0){System.out.print("Error, no se ejecuto");}
                cnx.close();
                dtmTurno.removeRow(fila);
            }catch(ClassNotFoundException cnfe){
                cnfe.printStackTrace();
            }catch(SQLException sqle){
                sqle.printStackTrace();
            }
       }
        
            
    }//GEN-LAST:event_jDescartarActionPerformed

    private void jTextDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDatoActionPerformed

                                

    }//GEN-LAST:event_jTextDatoActionPerformed

    private void jTextDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDatoKeyTyped
    char vChar = evt.getKeyChar();

        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }           
    }//GEN-LAST:event_jTextDatoKeyTyped
    private void limpiarTabla (){
        for(int i=0;i<jTableConsulta.getRowCount();i++){
            dtmTurno.removeRow(i);
            i--;
        }
    }
private String ObtenerFecha(){
    Calendar calr = new GregorianCalendar();
    SimpleDateFormat formato= new SimpleDateFormat("yyyy-MM-dd");
    int año = calr.get(Calendar.YEAR);
    int mes = calr.get(Calendar.MONTH)+1;
    int dia = calr.get(Calendar.DAY_OF_MONTH);
    String fecha=año+"-"+mes+"-"+dia;
    return(fecha);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jConsultar;
    private javax.swing.JButton jDescartar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextDato;
    private javax.swing.JRadioButton jradioDNI;
    private javax.swing.JRadioButton jradioNroTurno;
    // End of variables declaration//GEN-END:variables
}
