
package Turnos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

public class TurnoDoc extends javax.swing.JInternalFrame {
private DefaultTableModel dtmMedico;
   
 
    public TurnoDoc(int usr) {
        initComponents();
        
        try{
        Class.forName("org.gjt.mm.mysql.Driver");
        //Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123123");
        Connection cnx= DriverManager.getConnection("jdbc:mysql://localhost/cenMedico","root","123");
        Statement stm= cnx.createStatement();
        //ResultSet rst= stm.executeQuery("SELECT t.id,t.dni_paciente,e.nombre,t.fecha FROM turno t INNER JOIN medico m ON m.dni=t.dni_medico INNER JOIN usuario u ON u.id=m.id_usuario INNER JOIN estudio e ON e.id=t.id_estudio WHERE u.id="+usr+" and t.fecha >='"+ObtenerFecha()+" 00:00:00' and t.fecha<'"+ObtenerFechasig()+" 00:00:00' ;");
        ResultSet rst= stm.executeQuery("SELECT t.id,t.dni_paciente,e.nombre,t.fecha FROM turno t INNER JOIN medico m ON m.dni=t.dni_medico INNER JOIN usuario u ON u.id=m.id_usuario INNER JOIN estudio e ON e.id=t.id_estudio WHERE u.id="+usr+";");
        
        
        while(rst.next()){
        String [] registro= {rst.getString("id"),rst.getString("dni_paciente"),rst.getString("nombre"),rst.getString("fecha")};
        dtmMedico.addRow(registro);
        }
        cnx.close();
        }catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
        }catch (SQLException sqle){
            sqle.printStackTrace();
        }
    }
private String ObtenerFecha(){
    Calendar calr = new GregorianCalendar();
    SimpleDateFormat formato= new SimpleDateFormat("yyyy-MM-dd");
    int año = calr.get(Calendar.YEAR);
    int mes = calr.get(Calendar.MONTH)+1;
    int dia = calr.get(Calendar.DAY_OF_MONTH);
    String fecha=año+"-"+mes+"-"+dia;
    return(fecha);
}
private String ObtenerFechasig(){
    Calendar calr = new GregorianCalendar();
    SimpleDateFormat formato= new SimpleDateFormat("yyyy-MM-dd");
    int año = calr.get(Calendar.YEAR);
    int mes = calr.get(Calendar.MONTH)+1;
    int dia = calr.get(Calendar.DAY_OF_MONTH)+1;
    String fecha=año+"-"+mes+"-"+dia;
   System.out.println(fecha);
    return(fecha);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        String [] jTitulo = {"Nro","Dni Paciente","Estudio","Dia y Hora"};
        String [][] jDatos={};

        dtmMedico = new DefaultTableModel (jDatos,jTitulo);
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jTable1= new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(dtmMedico);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
